version: '3.1'
services:
  my-postgres-container:
    image: mypostgre:latest
    restart: always
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: productDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  my-spring-boot-app:
    image: product-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - my-postgres-container
    build: .